language: go
os:
        - osx
        - linux

go:
        - 1.7
        - 1.8
        - 1.9
        - tip

go_import_path: github.com/go-ble/ble

install:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then go get ./...; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then GOOS=linux go get && GOOS=linux go get ./linux; fi


script:
        - go vet ./...
        - go test -v ./...
        - GOOS=darwin go build -v ./...
        - GOOS=linux go build -v ./...
